Update fff

diff --git a/fff b/fff
--- a/fff
+++ b/fff
@@ -1,1 +1,34 @@
+pipeline {
+    agent any
+
+    stages {
+        stage('checkout') {
+            steps {
+                git branch: 'main', credentialsId: 'GIT_PATH', url: 'https://github.com/kanchana08/testing.git'
+            }
+        }
+        
+        stage('Hello') {
+            steps {
+                script {
+                    sh '''
+                        set -x
+                        screen -list
+                        if ! screen -list | grep -q 'my_screen_session'; then 
+                            echo "Creating screen session 'my_screen_session'"
+                            screen -dmS my_screen_session || { echo "Failed to create screen session"; exit 1; }
+                        fi
+                        
+                        if ! screen -list | grep -q 'my_screen_session2'; then 
+                            echo "Creating screen session 'my_screen_session2'"
+                            screen -dmS my_screen_session2 || { echo "Failed to create screen session"; exit 1; }
+                        fi
+                        
+                        screen -ls
+                    '''
+                }
+            }
+        }
+    }
+}
 
